import Head from "next/head";
import { Inter } from "@next/font/google";
import Homepage from "../components/template/Homepage";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Homepage />
      {/* <main>Where are the boys?, it seems they are all gorwn up</main> */}
    </>
  );
}
